version: '3.8'

services:
  db:
    container_name: nestjs-learning-db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME:-myapp}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - nestjs-learning

networks:
  nestjs-learning:
    driver: bridge

volumes:
  pg_data:
